- name: Install Hyperledger Caliper CLI
  hosts: all
  tasks:
    - name: Install Hyperledger Caliper CLI
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm install -g @hyperledger/caliper-cli
      args:
        executable: /bin/bash

    - name: Verify Hyperledger Caliper CLI installation
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm list -g --depth=0 | grep @hyperledger/caliper-cli
      register: caliper_cli_installed
      changed_when: false
      failed_when: false

    - name: Print installation status
      debug:
        msg: "Hyperledger Caliper CLI is {{ 'installed' if caliper_cli_installed.stdout else 'not installed' }}"